server:
  port: 8086

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**,/users/**,/admin/**

        - id: vet-service
          uri: lb://vet-service
          predicates:
            - Path=/vets/**

        - id: pet-service
          uri: lb://pet-service
          predicates:
            - Path=/pets/**

        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/appointments/**,/slots/**

        - id: visit-service
          uri: lb://visit-service
          predicates:
            - Path=/visits/**

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO

management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info